"""create with collation utf8

Revision ID: 075e05aa45f2
Revises: 
Create Date: 2018-12-11 18:13:00.788886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '075e05aa45f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('user_registration', sa.DateTime(), nullable=True),
    sa.Column('user_editcount', sa.Integer(), nullable=True),
    sa.Column('candidate_status', mysql.TINYTEXT(), nullable=True),
    sa.Column('invite_sent', mysql.TINYTEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_candidates_created_at'), 'candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_candidates_user_registration'), 'candidates', ['user_registration'], unique=False)
    op.create_table('predictions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), nullable=True),
    sa.Column('user_summary', mysql.JSON(), nullable=True),
    sa.Column('pred_min', sa.Float(), nullable=True),
    sa.Column('pred_mean', sa.Float(), nullable=True),
    sa.Column('pred_error', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_predictions_predicted_at'), 'predictions', ['predicted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_predicted_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_candidates_user_registration'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_created_at'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
