"""user_id cant be key for predicitons because many predictions to 1 user

Revision ID: 6c946cc45dd9
Revises: 
Create Date: 2018-12-12 12:51:23.381117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c946cc45dd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('user_registration', sa.DateTime(), nullable=True),
    sa.Column('user_editcount', sa.Integer(), nullable=True),
    sa.Column('candidate_status', mysql.TINYTEXT(), nullable=True),
    sa.Column('invite_sent', mysql.TINYTEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_candidates_created_at'), 'candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_candidates_user_registration'), 'candidates', ['user_registration'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=True),
    sa.Column('user_summary', mysql.JSON(), nullable=True),
    sa.Column('scores', mysql.JSON(), nullable=True),
    sa.Column('pred_min', sa.Float(), nullable=True),
    sa.Column('newcomer_predictions', mysql.JSON(), nullable=True),
    sa.Column('pred_error', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_predictions_predicted_at'), 'predictions', ['predicted_at'], unique=False)
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_predicted_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_candidates_user_registration'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_created_at'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
